In [1]:
# package imports
from  datetime import datetime, timedelta

import os, sys
import pandas as pd
import numpy as np 
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import matplotlib.pyplot as plt
%matplotlib inline

np.random.seed(2020)

# 端午节的淘宝粽子交易

In [40]:
zz = pd.read_csv('data/端午粽子数据.csv')
zz.columns = zz.columns.str.strip()
zz

                                     标题    价格      付款人数          店铺   发货地址
0      五芳斋粽子礼盒 心悦+18只装咸鸭蛋组合端午节礼品团购嘉兴肉粽子   129      6人付款    五芳斋官方旗舰店  浙江 嘉兴
1     北京稻香村端午粽子手工豆沙粽220g*2袋散装豆沙粽香甜软糯豆沙粽    44      8人付款        天猫超市     上海
2        五芳斋粽子礼盒装鲜肉咸蛋黄大肉粽嘉兴豆沙甜粽端午团购散装礼品  89.9  100万+人付款    五芳斋官方旗舰店  浙江 嘉兴
3        稻香私房鲜肉粽蛋黄肉粽嘉兴粽子咸鸭蛋礼盒装端午节送礼特产团购   138   1936人付款    稻香村食品旗舰店     北京
4        嘉兴粽子 蛋黄鲜肉粽新鲜大肉粽早餐散装团购浙江特产蜜枣多口味   3.8  9500+人付款       城城喂食猫  浙江 嘉兴
...                                 ...   ...       ...         ...    ...
4398  红船100克*2只五谷杂粮粽 浙江特产嘉兴粽子 团购粽子嘉兴端午节   7.9    347人付款       红船旗舰店  浙江 嘉兴
4399    隐栗古法烧肉粽/咸蛋黄/豆沙板栗端午粽子三种口味6只家庭礼盒装    93     80人付款   峨眉山隐栗粑粑罗栗  四川 乐山
4400     五芳斋 佛系粽子全素口味礼盒装桂花八宝粽豆沙甜粽端午礼品团购  98.2      5人付款      北京美程嘉译     北京
4401     【粉丝专享】端午节特产新鲜蛋黄鲜肉粽豆沙嘉兴粽子800g/箱  65.9    149人付款  chaoge1931  安徽 合肥
4402   粽子端午节送礼盒包装1200g双蛋黄广东东莞大个道滘裹蒸棕鲜肉粽    99     20人付款     hezhiqi  广东 东莞

[4403 rows x 5 columns]

In [42]:
zz.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4403 entries, 0 to 4402
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   标题      4403 non-null   object
 1   价格      4403 non-null   object
 2   付款人数    4332 non-null   object
 3   店铺      4403 non-null   object
 4   发货地址    4400 non-null   object
dtypes: object(5)
memory usage: 172.1+ KB

## temp

In [43]:
zz.columns

Index(['标题', '价格', '付款人数', '店铺', '发货地址'], dtype='object')

## 请删除最后一列为缺失值的行

In [44]:
#请删除最后一列为缺失值的行
zz = zz[zz['发货地址'].notna()]
zz

#查看异常的价格
zz[~zz['价格'].str.contains(r'^-?(\d+)(\.\d+)?$')]
zz = zz[zz['价格'].str.contains(r'^-?(\d+)(\.\d+)?$')]
#求所有在杭州发货的商品单价均值
zz[zz['发货地址'].str.contains('杭州')]['价格'].astype('float').mean()

                                     标题    价格      付款人数          店铺   发货地址
0      五芳斋粽子礼盒 心悦+18只装咸鸭蛋组合端午节礼品团购嘉兴肉粽子   129      6人付款    五芳斋官方旗舰店  浙江 嘉兴
1     北京稻香村端午粽子手工豆沙粽220g*2袋散装豆沙粽香甜软糯豆沙粽    44      8人付款        天猫超市     上海
2        五芳斋粽子礼盒装鲜肉咸蛋黄大肉粽嘉兴豆沙甜粽端午团购散装礼品  89.9  100万+人付款    五芳斋官方旗舰店  浙江 嘉兴
3        稻香私房鲜肉粽蛋黄肉粽嘉兴粽子咸鸭蛋礼盒装端午节送礼特产团购   138   1936人付款    稻香村食品旗舰店     北京
4        嘉兴粽子 蛋黄鲜肉粽新鲜大肉粽早餐散装团购浙江特产蜜枣多口味   3.8  9500+人付款       城城喂食猫  浙江 嘉兴
...                                 ...   ...       ...         ...    ...
4398  红船100克*2只五谷杂粮粽 浙江特产嘉兴粽子 团购粽子嘉兴端午节   7.9    347人付款       红船旗舰店  浙江 嘉兴
4399    隐栗古法烧肉粽/咸蛋黄/豆沙板栗端午粽子三种口味6只家庭礼盒装    93     80人付款   峨眉山隐栗粑粑罗栗  四川 乐山
4400     五芳斋 佛系粽子全素口味礼盒装桂花八宝粽豆沙甜粽端午礼品团购  98.2      5人付款      北京美程嘉译     北京
4401     【粉丝专享】端午节特产新鲜蛋黄鲜肉粽豆沙嘉兴粽子800g/箱  65.9    149人付款  chaoge1931  安徽 合肥
4402   粽子端午节送礼盒包装1200g双蛋黄广东东莞大个道滘裹蒸棕鲜肉粽    99     20人付款     hezhiqi  广东 东莞

[4400 rows x 5 columns]

/Users/maowei/anaconda3/lib/python3.7/site-packages/pandas/core/strings.py:1954: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

                                  标题     价格      付款人数        店铺   发货地址
538   五芳斋粽子蛋黄鲜肉粽豆沙粽栗子肉棕子新鲜散装批发团购嘉兴肉粽  45.9.  1.0万+人付款  五芳斋官方旗舰店  浙江 嘉兴
4376   东方贺礼端午节礼盒嘉兴粽子高汤蛋黄鲜大肉粽特产现已支持定制    45_     17人付款      缘来有礼  浙江 杭州

/Users/maowei/anaconda3/lib/python3.7/site-packages/pandas/core/strings.py:1954: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

81.10145251396636

## 商品标题带有“嘉兴”但发货地却不在嘉兴的商品有多少条记录？

In [45]:
zz[zz['标题'].str.contains('嘉兴') & ~zz['发货地址'].str.contains('嘉兴')]

                                     标题     价格     付款人数          店铺   发货地址
3        稻香私房鲜肉粽蛋黄肉粽嘉兴粽子咸鸭蛋礼盒装端午节送礼特产团购    138  1936人付款    稻香村食品旗舰店     北京
6          五芳斋华礼竹篮礼盒1360g蛋粽组合端午礼品嘉兴粽子礼盒    159  1028人付款        天猫超市     上海
8     真真老老嘉情礼盒10粽6蛋1.52kg/盒嘉兴粽子端午节粽子礼盒装    109  2117人付款        天猫超市     上海
9     五芳斋嘉兴粽子新鲜量贩蛋黄肉粽豆沙粽悦喜散装端午特产600g*2袋   59.9  1349人付款        天猫超市     上海
10         真真老老粽子臻芯800g/盒*1端午节礼盒装嘉兴特产送礼     75  1815人付款        天猫超市     上海
...                                 ...    ...      ...         ...    ...
4377      超港端午粽子肉粽蜜枣粽大肉棕子黄山特产礼盒新鲜嘉兴粽子肉粽   39.9    67人付款       超港旗舰店  安徽 黄山
4383     真真老老真情粽子咸蛋礼盒嘉兴特产肉粽豆沙甜枣粽端午节团购批发   79.9    10人付款     曈宝食品专营店     上海
4386     臻味德嘉兴粽子竹篮礼盒装农家手工蛋黄鲜肉棕甜粽端午节伴手礼品  49.08     2人付款       气泡西柚屋  浙江 温州
4393      傅太粽子10只蛋黄肉粽鲜肉粽嘉兴风味肉粽子即食早餐端午团购   60.2    46人付款      love侯氏  江西 萍乡
4401     【粉丝专享】端午节特产新鲜蛋黄鲜肉粽豆沙嘉兴粽子800g/箱   65.9   149人付款  chaoge1931  安徽 合肥

[1031 rows x 5 columns]

## 请按照分位数将价格分为“高、较高、中、较低、低”5 个类别，再将类别结果插入到标题一列之后，最后对类别列进行降序排序

In [46]:
zz['价格'] = zz['价格'].astype('float')

In [48]:
zz['类别'] = pd.qcut(zz['价格'],[0,0.2,0.4,0.6,0.8,1.],labels=['低','较低','中','较高','高'])
zz.sort_values('类别', ascending=False)

                                    标题      价格    付款人数         店铺   发货地址 类别
0     五芳斋粽子礼盒 心悦+18只装咸鸭蛋组合端午节礼品团购嘉兴肉粽子  129.00    6人付款   五芳斋官方旗舰店  浙江 嘉兴  高
660     五芳斋粽子百年五芳礼品粽大肉粽豆沙粽嘉兴粽子礼盒装 批发团购  328.00   20人付款    伟弘食品专营店     上海  高
1199    三全嘉兴粽子礼盒装鸭蛋黄肉粽端午手工蜜枣甜粽特产真空鲜肉棕子  138.00   43人付款  三全京之良品专卖店  河北 廊坊  高
1945     好利来礼盒粽子好礼香棕顺丰包邮沈阳发货员工福利采购团购优惠  109.00   11人付款      木宝很开心  辽宁 沈阳  高
1197     诸老大粽子诸事欢禧礼盒嘉兴特产蛋黄黑猪肉粽咸蛋端午送礼团购  180.00   20人付款     诸老大旗舰店  浙江 嘉兴  高
...                                ...     ...     ...        ...    ... ..
2130     三珍斋蛋黄粽200g真空100g*2只嘉兴特产粽子速食早餐    7.88     NaN      天猫会员店     上海  低
3637    新鲜粽叶包粽子的叶子干粽子叶大号竹子叶竹叶苇叶皮大鲜粽叶干种    4.00  617人付款    海倪食品专营店  广东 广州  低
2131     俏香阁经典鲜肉粽子120g*2只端午节嘉兴特产速食早餐点心    5.90     NaN      天猫会员店     上海  低
1259    五芳斋粽子鲜肉蛋黄板栗大肉豆沙粽早餐散装团购批发特产嘉兴粽子   21.90  417人付款    红船食品专营店  江苏 南京  低
2916    甜粽子蜜枣粽端午送人礼品豆沙粽红豆赤豆粽方便早餐素棕散装团购   21.90  230人付款    集采食品专营店  浙江 嘉兴  低

[4398 rows x 6 columns]

## 付款人数一栏有缺失值吗？若有则请利用上一问的分类结果对这些缺失值进行合理估计并填充

In [49]:
zz[zz.付款人数.isna()]

                                     标题      价格 付款人数     店铺 发货地址  类别
183   五芳斋 140g*8只大粽子 福韵端午豆沙蜜枣蛋黄粽新包装送礼礼盒   50.90  NaN  天猫会员店   上海   中
243           五芳斋福雅五芳粽子礼盒端午咸甜粽子绿豆糕咸鸭蛋送礼   79.90  NaN  天猫会员店   上海  较高
347         【百草味】龙腾粽1090g 早餐大肉粽子湖州特产嘉兴粽   39.90  NaN  天猫会员店   上海   中
386        五芳斋华礼竹篮礼盒1360g蛋粽组合端午礼品嘉兴粽子礼盒  129.00  NaN  天猫会员店   上海   高
389     百草味 龙腾粽礼盒1460g 10只装早餐大肉粽子湖州特产嘉兴   49.90  NaN  天猫会员店   上海   中
...                                 ...     ...  ...    ...  ...  ..
2025           真真老老 嘉兴肉粽 130g 真空 粽子 端午节    4.50  NaN  天猫会员店   上海   低
2077           真真老老 嘉兴肉粽 130g 真空 粽子 端午节    4.50  NaN  天猫会员店   上海   低
2078      俏香阁蛋黄鲜肉粽子120g*2只端午节嘉兴特产速食早餐点心    5.90  NaN  天猫会员店   上海   低
2130      三珍斋蛋黄粽200g真空100g*2只嘉兴特产粽子速食早餐    7.88  NaN  天猫会员店   上海   低
2131      俏香阁经典鲜肉粽子120g*2只端午节嘉兴特产速食早餐点心    5.90  NaN  天猫会员店   上海   低

[71 rows x 6 columns]

# 墨尔本每日最低温度

In [55]:
df = pd.read_csv('data/墨尔本温度数据.csv')
df
df.info()
df['Date'] = pd.to_datetime(df['Date'])

            Date  Temp
0     1981-01-01  20.7
1     1981-01-02  17.9
2     1981-01-03  18.8
3     1981-01-04  14.6
4     1981-01-05  15.8
...          ...   ...
3645  1990-12-27  14.0
3646  1990-12-28  13.6
3647  1990-12-29  13.5
3648  1990-12-30  15.7
3649  1990-12-31  13.0

[3650 rows x 2 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3650 entries, 0 to 3649
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    3650 non-null   object
 1   Temp    3650 non-null   float64
dtypes: float64(1), object(1)
memory usage: 57.2+ KB

## 剔除国庆节、五一劳动节和每月第一个周一，求每月的平均最低气温

In [56]:
df['year'] = df.Date.apply(lambda x:x.year)
df['month'] = df.Date.apply(lambda x:x.month)
df['day'] = df.Date.apply(lambda x:x.day)
df['weekday'] = df.Date.apply(lambda x:x.weekday())

# 2016 年 8 月上海市摩拜单车骑行记录

In [61]:
df = pd.read_csv('data/摩拜单车数据.csv')
df.info()
df['start_time'] = pd.to_datetime(df['start_time'])
df['end_time'] = pd.to_datetime(df['end_time'])
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102361 entries, 0 to 102360
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   orderid           102361 non-null  int64
 1   bikeid            102361 non-null  int64
 2   userid            102361 non-null  int64
 3   start_time        102361 non-null  object
 4   start_location_x  102361 non-null  float64
 5   start_location_y  102361 non-null  float64
 6   end_time          102361 non-null  object
 7   end_location_x    102361 non-null  float64
 8   end_location_y    102361 non-null  float64
 9   track             102361 non-null  object
dtypes: float64(4), int64(3), object(3)
memory usage: 7.8+ MB

,orderid,bikeid,userid,start_time,start_location_x,start_location_y,end_time,end_location_x,end_location_y,track
0,78387,158357,10080,2016-08-20 06:57:00,121.348,31.389,2016-08-20 07:04:00,121.357,31.388,"121.347,31.392#121.348,31.389#121.349,31.390#1..."
1,891333,92776,6605,2016-08-29 19:09:00,121.508,31.279,2016-08-29 19:31:00,121.489,31.271,"121.489,31.270#121.489,31.271#121.490,31.270#1..."
2,1106623,152045,8876,2016-08-13 16:17:00,121.383,31.254,2016-08-13 16:36:00,121.405,31.248,"121.381,31.251#121.382,31.251#121.382,31.252#1..."
3,1389484,196259,10648,2016-08-23 21:34:00,121.484,31.320,2016-08-23 21:43:00,121.471,31.325,"121.471,31.325#121.472,31.325#121.473,31.324#1..."
4,188537,78208,11735,2016-08-16 07:32:00,121.407,31.292,2016-08-16 07:41:00,121.418,31.288,"121.407,31.291#121.407,31.292#121.408,31.291#1..."
...,...,...,...,...,...,...,...,...,...,...
102356,1479550,214335,1423,2016-08-28 18:03:00,121.478,31.297,2016-08-28 18:09:00,121.481,31.304,"121.478,31.297#121.479,31.297#121.480,31.297#1..."
102357,1478273,160487,3067,2016-08-14 20:22:00,121.320,31.238,2016-08-14 20:28:00,121.312,31.235,"121.312,31.235#121.313,31.235#121.313,31.236#1..."
102358,367733,179530,12746,2016-08-27 09:54:00,121.391,31.307,2016-08-27 10:06:00,121.398,31.306,"121.390,31.307#121.391,31.307#121.392,31.307#1..."
102359,64915,167419,837,2016-08-20 06:04:00,121.515,31.269,2016-08-20 06:10:00,121.510,31.272,"121.510,31.272#121.510,31.273#121.511,31.273#1..."
102360,326987,63172,2547,2016-08-09 10:51:00,121.521,31.261,2016-08-09 11:01:00,121.518,31.274,"121.518,31.274#121.519,31.270#121.519,31.271#1..."

## 平均而言，周末单天用车量比工作日单天用车量更大吗？

In [ ]:
df['使用时长'] = df.end_time - df.start_time

In [62]:
df['weekday'] = df.start_time.apply(lambda x: x.weekday())

In [64]:
df.weekday.value_counts().sort_index()

0    16380
1    16259
2    17829
3    12484
4    13208
5    13359
6    12842
Name: weekday, dtype: int64

## 工作日每天的高峰时间段大致为上午 7:30 至 9:30、下午 17:00 至 19:00， 请问 8 月里早高峰骑行记录量（以 start_time 为准）高于晚高峰的有 几天？

In [66]:
temp = df.copy()
temp['time'] = df.start_time.apply(lambda x: x.time())
con1 = temp['start_time']>'7:30' & temp['start_time']>'7:30'
temp[con1]

TypeError: unsupported operand type(s) for &: 'str' and 'DatetimeArray'